modLoader="javafml"
loaderVersion="${loader_version}"
license="All rights reserved"
issueTrackerURL="https://github.com/henkelmax/ultimate-car-mod/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://update.maxhenkel.de/neoforge/car"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod"
authors="${mod_vendor}"
description='''This mod brings cars, road construction and biodiesel production into your Minecraft world'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="jei"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="theoneprobe"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="jade"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"